# WARNING - Generated by {fusen} from dev/dev_plot_Region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Main country of Asylum in the Region
#'
#' @param year Numeric value of the year (for instance 2020)
#' @param region Character value with the related UNHCR bureau - when left null,
#'               it will display the whole world
#' @param top_n_countries Numeric value of number of main countries that the graph should display
#' @param pop_type Character value. Possible population type
#'                 (e.g.: REF, IDP, ASY, OIP, OOC, STA)
#' @param show_diff_label logical to indicate whether or not adding the the label displaying difference in percentage compared to the previous year
#'
#' @importFrom ggplot2 ggplot aes geom_bar geom_label geom_hline coord_flip labs scale_y_continuous element_line element_blank
#' @importFrom dplyr filter mutate select rename group_by summarise arrange desc case_when
#' @importFrom countrycode countrycode
#' @importFrom scales label_number cut_short_scale
#' @importFrom unhcrthemes theme_unhcr
#' @importFrom stats reorder
#' @importFrom utils head
#'
#' @return a ggplot2 object
#'
#' @export
#' @examples
#' plot_reg_population_type_abs(
#'   year = 2024,
#'   region = "The Americas",
#'   top_n_countries = 5,
#'   pop_type = "REF",
#'   show_diff_label = TRUE
#' )
#'
#' plot_reg_population_type_abs(
#'   year = 2024,
#'   region = "The Americas",
#'   top_n_countries = 5,
#'   pop_type = "ASY",
#'   show_diff_label = FALSE
#' )
plot_reg_population_type_abs <- function(year = 2024,
                                         region = "The Americas",
                                         top_n_countries = 5,
                                         pop_type = "REF",
                                         show_diff_label = TRUE) {
  pop_type_label_dict <- c(
    "REF" = "Refugees",
    "ASY" = "Asylum-seekers",
    "IDP" = "Internally displaced persons",
    "OIP" = "Other people in need of international protection",
    "STA" = "Stateless people",
    "OOC" = "Others of concern to UNHCR",
    "HST" = "Host community"
  )

  pop_type_col <- dplyr::case_when(
    pop_type == "REF" ~ "refugees",
    pop_type == "ASY" ~ "asylum_seekers",
    pop_type == "IDP" ~ "idps",
    pop_type == "OIP" ~ "oip",
    pop_type == "STA" ~ "stateless",
    pop_type == "OOC" ~ "ooc",
    pop_type == "HST" ~ "hst",
    TRUE ~ "refugees"
  )

  df <- refugees::population |>
    dplyr::filter(year == !!year) |>
    dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region")) |>
    dplyr::filter(unhcr_region == region) |>
    dplyr::select(coa_name, !!pop_type_col) |>
    dplyr::rename(value = !!pop_type_col) |>
    dplyr::group_by(coa_name) |>
    dplyr::summarise(value = sum(value, na.rm = TRUE)) |>
    dplyr::arrange(dplyr::desc(value)) |>
    utils::head(top_n_countries)

  p <- ggplot2::ggplot(df, ggplot2::aes(x = stats::reorder(coa_name, value), y = value)) +
    ggplot2::geom_bar(stat = "identity", position = "identity", fill = "#0072bc") +
    ggplot2::geom_label(
      ggplot2::aes(
        x = coa_name,
        y = value,
        label = scales::label_number(scale_cut = scales::cut_short_scale())(value)
      ),
      hjust = 1,
      vjust = 0.5,
      colour = "white",
      fill = NA,
      label.size = NA,
      family = "Lato",
      size = 6
    ) +
    ggplot2::geom_hline(yintercept = 0, size = 1, colour = "#333333") +
    ggplot2::coord_flip() +
    ggplot2::labs(
      title = paste0("Top ", top_n_countries, " ", pop_type_label_dict[pop_type], " hosting countries"),
      subtitle = paste0("In ", region, " as of ", year),
      x = "",
      y = "",
      caption = "Source: UNHCR.org/refugee-statistics"
    ) +
    ggplot2::scale_y_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
    unhcrthemes::theme_unhcr(
      grid = "X",
      axis = "y",
      axis_title = "x",
      font_size = 14
    ) +
    ggplot2::theme(
      panel.grid.major.x = ggplot2::element_line(color = "#cbcbcb"),
      panel.grid.major.y = ggplot2::element_blank()
    )

  return(p)
}
